objects/Account.object
<CustomObject>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as a part to relate only Branches to Store account</description>
        <label>Parent Branch</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Seller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Visit Plan</label>
        <referenceTo>Visit_Plan__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Visit_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Accounts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created to remove error</description>
        <label>Accounts</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits Plan (Accounts)</relationshipLabel>
        <relationshipName>Visits_Plan1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <formula>TEXT(  Account__r.Frequency__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Frequency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Friday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Saturday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Saturday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Seller_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Branch, Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Visits Plan</relationshipLabel>
        <relationshipName>Visits_Plan</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sunday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created for Visit Plan</description>
        <label>Sunday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Thursday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Thursday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WK1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WK1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WK2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WK2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WK3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WK3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WK4__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WK4</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WK5__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WK5</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </fields>
    <label>Visit Plan</label>
    <nameField>
        <label>Visit Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/visitplancontroller.cls
public class visitplancontroller {

    @AuraEnabled
    public static list<wrapperclass> fetchVisits(string accountId, string contactId) {
        
        list<wrapperclass> wrapperclassList = new list<wrapperclass>();
        
        list<Account> storeList = [SELECT ID, Name, Parent_Branch__c, Seller_Name__c, Frequency__c, Seller_Name__r.Name, Visit_Plan__c 
                           FROM Account 
                           WHERE Parent_Branch__c =: accountId AND Seller_Name__c =: contactId];
        
        Contact conList = [SELECT ID, Name from Contact where ID =: contactId];
        
        for(Account tempStore : storeList) {
            wrapperclass newWrapClass;
            if(tempStore.Visit_Plan__c != null) {
                Visit_Plan__c vpList = [SELECT ID, Frequency__c, Sunday__c, Monday__c, Tuesday__c, Wednesday__c, Thursday__c, Friday__c, Saturday__c, WK1__c, WK2__c, WK3__c, WK4__c, WK5__c, Seller_Name__c, Seller_Name__r.Name 
                                        FROM Visit_Plan__c 
                                        WHERE ID =: tempStore.Visit_Plan__c];
                
                newWrapClass = new wrapperclass(tempStore.ID, tempStore.Name, conList.ID, conList.Name, vpList.Frequency__c, vpList.Monday__c, vpList.Tuesday__c, vpList.Wednesday__c, vpList.Thursday__c, vpList.Friday__c, vpList.Saturday__c,
                                                  vpList.Sunday__c, vpList.WK1__c, vpList.WK2__c, vpList.WK3__c, vpList.WK4__c, vpList.WK5__c, vpList.Id);
            }
            else {
                newWrapClass = new wrapperclass(tempStore.ID, tempStore.Name, conList.ID, conList.Name, tempStore.Frequency__c, false, false, false, false, false, false, false, false, false, false, false, false, '');
            }
            wrapperclassList.add(newWrapClass);
        }
        return wrapperclassList;
    }
    
    @AuraEnabled
    public static list <Visit_Plan__c> fetchAllVisits(string accountId) {
        list<Account> accountList = [SELECT ID, Name, Visit_Plan__c FROM Account WHERE ID =: accountId];
        list<ID> visitPlanIDList = new list<ID>();
        for(Account tempAcc : accountList) {
            visitPlanIDList.add(tempAcc.Visit_Plan__c);
        }
        list<Visit_Plan__c> allVisitPlansList = [SELECT ID, Name, Accounts__c, Thursday__c, Frequency__c,
                                                 WK1__c, WK2__c, WK3__c, WK4__c, WK5__c, Sunday__c, Saturday__c,
                                                 Friday__c, Wednesday__c, Accounts__r.name, Seller_Name__c,
                                                 Seller_Name__r.Name, Monday__c, Tuesday__c
                                                 FROM Visit_Plan__c WHERE ID IN: visitPlanIDList];
        return allVisitPlansList;
    }

    @AuraEnabled
    public static id savevisitplan(string wcs) {
        string idd = NULL;
        system.debug('########'+wcs);
        if (wcs != NULL) {
            list < wrapperclass > wrapperclassList = (list < wrapperclass > ) System.JSON.deserialize(wcs, list < wrapperclass >.class);
            list < Visit_Plan__c > vpUpsertList = new list < Visit_Plan__c > ();
            list<Account> accList = [SELECT ID, Visit_Plan__c 
                                     FROM Account];
            list<Account> accountToUpdate = new list<Account>();
            
            for (wrapperclass wc: wrapperclassList) {
                
                system.debug(wc.vpid.length());
                Visit_Plan__c vp = new Visit_Plan__c();
                vp.name = wc.accName + 'Plan ' + Date.Today().format();
                vp.Accounts__c = wc.accID;
                vp.Seller_Name__c = wc.conID;
                vp.Monday__c = wc.mon;
                vp.Tuesday__c = wc.tue;
                vp.Wednesday__c = wc.wed;
                vp.Thursday__c = wc.thur;
                vp.Friday__c = wc.fri;
                vp.Saturday__c = wc.sat;
                vp.Sunday__c = wc.sun;
                vp.WK1__c = wc.week1;
                vp.WK2__c = wc.week2;
                vp.WK3__c = wc.week3;
                vp.WK4__c = wc.week4;
                vp.WK5__c = wc.week5;
                if(wc.vpid.length() > 0) {
                    vp.id = wc.vpid;
                }
                vpUpsertList.add(vp);
            }

            upsert vpUpsertList;
            idd = vpUpsertList[0].id;
            
            for(wrapperclass wc: wrapperclassList) {
                for(Account tempAcc : accList) {
                    if(tempAcc.ID == wc.accID) {
                        for(Visit_Plan__c tempVC : vpUpsertList) {
                            if(tempVC.Accounts__c == wc.accID && tempVC.Seller_Name__c == wc.conID) {
                                tempAcc.Visit_Plan__c = tempVC.ID;
                                accountToUpdate.add(tempAcc);
                            }
                        }
                    }
                }
            }
            system.debug('££££'+accountToUpdate);
            update accountToUpdate;

        }
        return idd;
    }

    public class wrapperclass {
        
        @AuraEnabled
        public string accID {
            get;
            set;
        }
        
        @AuraEnabled
        public string accName {
            get;
            set;
        }
        
        @AuraEnabled
        public string conID {
            get;
            set;
        }
        
        @AuraEnabled
        public string conName {
            get;
            set;
        }

        @AuraEnabled
        public string frequency {
            get;
            set;
        }

        @AuraEnabled
        public boolean mon {
            get;
            set;
        }

        @AuraEnabled
        public boolean tue {
            get;
            set;
        }

        @AuraEnabled
        public boolean wed {
            get;
            set;
        }

        @AuraEnabled
        public boolean thur {
            get;
            set;
        }

        @AuraEnabled
        public boolean fri {
            get;
            set;
        }

        @AuraEnabled
        public boolean sat {
            get;
            set;
        }

        @AuraEnabled
        public boolean sun {
            get;
            set;
        }

        @AuraEnabled
        public boolean week1 {
            get;
            set;
        }

        @AuraEnabled
        public boolean week2 {
            get;
            set;
        }

        @AuraEnabled
        public boolean week3 {
            get;
            set;
        }

        @AuraEnabled
        public boolean week4 {
            get;
            set;
        }

        @AuraEnabled
        public boolean week5 {
            get;
            set;
        }

        @AuraEnabled
        public string vpid {
            get;
            set;
        }

        public wrapperclass(String accID, String accName, String conID, string con, string freq, boolean mon, boolean tue, boolean wed, boolean thur, boolean fri, boolean sat, boolean sun, boolean week1, boolean week2, boolean week3, boolean week4, boolean week5, string vpid) {
            this.accID = accID;
            this.accName = accName;
            this.conID = conID;
            this.conName = con;
            this.frequency = freq;
            this.mon = mon;
            this.tue = tue;
            this.wed = wed;
            this.thur = thur;
            this.fri = fri;
            this.sat = sat;
            this.sun = sun;
            this.week1 = week1;
            this.week2 = week2;
            this.week3 = week3;
            this.week4 = week4;
            this.week5 = week5;
            this.vpid = vpid;
        }

    }

}