objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <label>Branch Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distributor_Code__c</fullName>
        <externalId>true</externalId>
        <label>Distributor Code</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Local_Channel_Code__c</fullName>
        <description>Created as a dependent field to Sub Channel Code for Store Account</description>
        <globalPicklist>ChannelCodePicklist</globalPicklist>
        <label>Local Channel Code</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StoreCode__c</fullName>
        <label>Store Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Channel_Code__c</fullName>
        <description>Created by Faizan to act as controlling field for local channel code</description>
        <globalPicklist>ChannelCodePicklist</globalPicklist>
        <label>Sub Channel Code</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Visit Plan</label>
        <referenceTo>Visit_Plan__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <formula>Account.Parent.Branch_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Branch Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distributor_Code__c</fullName>
        <formula>Account.Parent.Parent.Distributor_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Distributor Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RelatedContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visit_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <formula>Account__r.Parent.Branch_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Branch Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distributor_Code__c</fullName>
        <formula>Account__r.Parent.Parent.Distributor_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Distributor Code</label>
        <type>Text</type>
    </fields>
    <label>Visit Plan</label>
    <nameField>
        <label>Visit Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContactService.cls
public class ContactService {
    public static List<Contact> getContactsByUserId(Id userId) {
        List<Contact> contactList = [
                                        SELECT
                                            Id,
                                            Distributor_Code__c,
                                            Account.Name,
                                            Branch_Code__c,
                                            Name,
                                            Related_User__r.Name,
                                            Related_User__r.TimeZoneSidKey,
                                            MailingStreet,
                                            MobilePhone,
                                            Related_User__r.UserRole.Name,
                                            Related_User__r.UserName,
                                            Account.StoreCode__c,
                                            Account.Visit_Plan__c,
                                            Account.Sub_Channel_Code__c,
                                            Account.Local_Channel_Code__c,
                                            Account.Lat_and_Long__Latitude__s,
                                            Account.Lat_and_Long__Longitude__s
                                        FROM
                                            Contact
                                        WHERE
                                            Related_User__c = :userId
                                            
        ];
        return contactList;
    }
}