objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <label>Branch Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distributor_Code__c</fullName>
        <externalId>true</externalId>
        <label>Distributor Code</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Local_Channel_Code__c</fullName>
        <description>Created as a dependent field to Sub Channel Code for Store Account</description>
        <globalPicklist>ChannelCodePicklist</globalPicklist>
        <label>Local Channel Code</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StoreCode__c</fullName>
        <label>Store Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Channel_Code__c</fullName>
        <description>Created by Faizan to act as controlling field for local channel code</description>
        <globalPicklist>ChannelCodePicklist</globalPicklist>
        <label>Sub Channel Code</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Visit Plan</label>
        <referenceTo>Visit_Plan__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <formula>Account.Parent.Branch_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Branch Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distributor_Code__c</fullName>
        <formula>Account.Parent.Parent.Distributor_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Distributor Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RelatedContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visit_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <formula>Account__r.Parent.Branch_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Branch Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distributor_Code__c</fullName>
        <formula>Account__r.Parent.Parent.Distributor_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Distributor Code</label>
        <type>Text</type>
    </fields>
    <label>Visit Plan</label>
    <nameField>
        <label>Visit Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContactTranslator.cls
global class ContactTranslator {
    global static List<ContactDomain.UserInfo> objectToUserInfo(List<Contact> contactList) {
        List<ContactDomain.UserInfo> contactInfoList = new List<ContactDomain.UserInfo>();
        for(Contact con : contactList) {
            ContactDomain.UserInfo userInfo = new ContactDomain.UserInfo();
            userInfo.DistributorId = con.Distributor_Code__c;
            userInfo.DistributorName = con.Account.Name;
            userINfo.BranchId = con.Branch_Code__c;
            userInfo.UserName = con.Related_User__r.UserName;
            userInfo.LoginId = con.Related_User__r.Name;
            userInfo.Timezone = con.Related_User__r.TimeZoneSidKey;
            userInfo.Address1 = con.MailingStreet;
            userInfo.UserType = con.Related_User__r.UserRole.Name;
            userInfo.CurrentDate = DateTime.now().format('dd/MM/yyyy');
            contactInfoList.add(userInfo);
        }
        return contactInfoList;
    }
    
    global static List<ContactDomain.RetailerInfo> objectToRetailerInfo(List<Contact> contactList) {
        List<ContactDomain.RetailerInfo> retailerInfoList = new List<ContactDomain.RetailerInfo>();
        for(Contact con : contactList) {
            ContactDomain.RetailerInfo retailerInfo = new ContactDomain.RetailerInfo();
            retailerInfo.SellerId = con.Id;
            retailerInfo.RetailerCode = con.Account.StoreCode__c;
            retailerInfo.RetailerName = con.Account.Name;
            retailerInfo.Address1 = con.MailingStreet;
            retailerInfo.BeatId = con.Account.Visit_Plan__c;
            retailerInfo.ChannelId = con.Account.Local_Channel_Code__c;
            retailerInfo.Latitude = con.Account.Lat_and_Long__Latitude__s;
            retailerInfo.Longitude = con.Account.Lat_and_Long__Longitude__s;
            retailerInfo.SubChannelId = con.Account.Sub_Channel_Code__c;
            retailerInfoList.add(retailerInfo);
        }
        return retailerInfoList;
    }
    
}