objects/Account.object
<CustomObject>
    <fields>
        <fullName>Parent_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as a part to relate only Branches to Store account</description>
        <label>Parent Branch</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Seller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Branch</fullName>
        <active>true</active>
        <label>Branch</label>
    </recordTypes>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <label>Store</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Seller</fullName>
        <active>true</active>
        <label>Seller</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestVisitPlanController.cls
/**********************************************************************\
    @ Author        : Souravmoy Gorai
    @ Date          : December 15, 2016
    @ Test File     : Yes
    @ Function      : Test Class for visitplancontroller
***********************************************************************/

@isTest
private class TestVisitPlanController {

    static testMethod void myUnitTest() {
        Test.startTest();
        	list<Account> testAccBrachList = TestDataUtility.createAccountTestData('Branch');
        	Database.insert(testAccBrachList);
        	list<Contact> testConList = TestDataUtility.createContactTestData('Seller');
        	for(Contact tempSeller : testConList)
        		tempSeller.AccountID = testAccBrachList[0].ID;
    		Database.insert(testConList);
        	list<Account> testAccStoreList = TestDataUtility.createAccountTestData('Store');
        	for(Account tempStore : testAccStoreList) {
        		tempStore.Parent_Branch__c = testAccBrachList[0].ID;
        		tempStore.Seller_Name__c = testConList[0].ID; 
        	}
        	Database.insert(testAccStoreList);
    		
        	visitplancontroller vpc = new visitplancontroller();
        	visitplancontroller.fetchVisits(testAccBrachList[0].ID,testConList[0].ID);
        	String newVisitPlan = '[{"accID":"'+testAccStoreList[0].ID+'","accName":"'+testAccStoreList[0].Name+'","conID":"'+testConList[0].ID+'","conName":"'+testConList[0].Name+'","fri":false,"mon":true,"sat":false,"sun":false,"thur":false,"tue":true,"vpid":"","wed":false,"week1":true,"week2":false,"week3":false,"week4":false,"week5":false}]';
        	visitplancontroller.savevisitplan(newVisitPlan);
        	visitplancontroller.fetchVisits(testAccBrachList[0].ID,testConList[0].ID);
        	visitplancontroller.fetchAllVisits(testAccBrachList[0].ID);
        Test.stopTest();
    }
}