objects/Account.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <formula>Parent.Distributor_Code__c</formula>
        <label>Distributor Code</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Store</fullName>
        <active>true</active>
        <label>Store</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>DateTime</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Questions</relationshipLabel>
        <relationshipName>Survey_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ-{000}</displayFormat>
        <label>Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey_Result__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seller__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Store</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Survey Result</label>
    <nameField>
        <label>Survey Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey_Result_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Actual__c</fullName>
        <label>Actual</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Survey Results Detail</relationshipLabel>
        <relationshipName>Survey_Results_Detail</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_Result__c</fullName>
        <label>Survey Result</label>
        <referenceTo>Survey_Result__c</referenceTo>
        <relationshipLabel>Survey Results Detail</relationshipLabel>
        <relationshipName>Survey_Results_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Result Detail</label>
    <nameField>
        <label>Survey Result Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Results Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestRESTOptionManager.cls
@isTest
private class TestRESTOptionManager {

    static testMethod void optionManager() {
        
        List<RecordType> rtlist = [SELECT ID, DeveloperName, SObjectType  
                                        FROM RecordType 
                                    WHERE SObjectType = 'Account' 
                                    AND DeveloperName = 'Store'];
                                    
        Account acc = new Account (Name = 'test');
        if (rtlist != null && rtlist.size() > 0) {
            acc.recordtypeId = rtlist[0].Id;
        }
        insert acc;
        
        Contact con = new Contact (LastName = 'test');
        insert con;
        
        Survey__c servey = new Survey__c(Name = 'testservey');
        insert servey;
        
        Survey_Question__c sq = new Survey_Question__c(Question__c = 'what is your question?', From__c = system.now());
        insert sq;
        
        Survey_Result__c sr = new Survey_Result__c(Code__c = 'code123', Survey__c = servey.Id, Seller__c = con.Id, Store__c = acc.Id);
        insert sr;
        
        Survey_Result_Detail__c srd = new Survey_Result_Detail__c(Survey_Result__c = sr.Id, Survey_Question__c = sq.Id, Actual__c = '10');
        insert srd; 
        
        List<SurveyResultDetailDomain.SurveyResultDetailInfo> serveyResult = RESTOptionManager.getOptions();
        
    }
}