objects/Account.object
<CustomObject>
    <fields>
        <fullName>Parent_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as a part to relate only Branches to Store account</description>
        <label>Parent Branch</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Seller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Visit Plan</label>
        <referenceTo>Visit_Plan__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Visit_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits Plan</relationshipLabel>
        <relationshipName>Visits_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Accounts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created to remove error</description>
        <label>Accounts</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits Plan (Accounts)</relationshipLabel>
        <relationshipName>Visits_Plan1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Branch, Store</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Visits Plan</relationshipLabel>
        <relationshipName>Visits_Plan</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Visit Plan</label>
    <nameField>
        <label>Visit Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/VisitPlan.cls
public with sharing class VisitPlan{
 
 public Visit_Plan__c vp{get; set;}
 public List<Visit_Plan__c> newVPList{get; set;}

    public VisitPlan(ApexPages.StandardController stdController){
        vp = new Visit_Plan__c();
    }
    
    public void fetchVP(){
        try{
            newVPList = new List<Visit_Plan__c>();
            Visit_Plan__c tempVP;
            Set<ID> ConID=new Set<ID>();
            List<Contact> lstCon= [select id,name from Contact where AccountID =: vp.Account__c];
            System.debug(lstCon);
            If(lstCon != NULL){
            for(Contact c: lstCon){
            conID.add(c.id);
            }
            List<Account> lstAcc = [Select Id, Name,Parent_Branch__c from Account where Seller_Name__c =:conID and Seller_Name__c =:vp.Seller_Name__c ];
            for(Account a: lstAcc){
                tempVP = new Visit_Plan__c();
                tempVP.Seller_Name__c = vp.Seller_Name__c;
                tempVP.Accounts__c = a.id; 
                //tempVP.Account__c = a.Parent_Branch__c;
                tempVP.Name = a.Name + 'Plan ' + Date.Today().format();  
                
                newVPList.add(tempVP);                
            }
            }
            else{
           ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'ConTactList Empty'));
           } 
            
        }catch(Exception e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,e.getMessage()));
            
        }
     }
     
     public PageReference saveVP(){
         try{
            System.Debug(newVPList);
            insert newVPList; 
            String id = ApexPages.CurrentPage().getparameters().get('id');
            string urlId = label.VisitPlanId;
            pagereference ref = new pageReference('/'+urlId);
            return ref;
                               
        }catch(Exception e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,e.getMessage()));
            return null;
            
        }

    }     
 
 }