objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Related_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RelatedContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visit__c.object
<CustomObject>
    <description>Created on 01-12-2016 to capture Visit done to a store</description>
    <fields>
        <fullName>Original_Date__c</fullName>
        <description>Date on which the original visit was supposed to happen</description>
        <label>Original Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Seller who visited the store</description>
        <label>Seller</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestRESTBeatManager.cls
@isTest
private class TestRESTBeatManager {
    
    static testMethod void beatManager1() {
        Contact con = new Contact(LastName = 'TestLast', Related_User__c = UserInfo.getUserId());
        insert con;
        
        List<Visit__c> visitList = new List<Visit__c> {
            new Visit__c(Seller__c = con.Id, Original_Date__c = date.today()),
            new Visit__c(Seller__c = con.Id, Original_Date__c = date.today()),
            new Visit__c(Seller__c = con.Id, Original_Date__c = date.today()),
            new Visit__c(Seller__c = con.Id, Original_Date__c = date.today())
        };
        insert visitList;
        VisitDomain.VisitInfo vi = new VisitDomain.VisitInfo();
        vi.RouteId = 1;
        vi.TodayRoute = 3;
        vi.RouteName = 'test';       
        List<VisitDomain.VisitInfo> visitInfoList = RESTBeatManager.getBeats();
    }
}