objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Related_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RelatedContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visit__c.object
<CustomObject>
    <description>Created on 01-12-2016 to capture Visit done to a store</description>
    <fields>
        <fullName>Original_Date__c</fullName>
        <description>Date on which the original visit was supposed to happen</description>
        <label>Original Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route_Id__c</fullName>
        <label>Route Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Seller who visited the store</description>
        <label>Seller</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/VisitService.cls
public with sharing class VisitService {
    
    //Get all the Visit Records of an user
    public static List<Visit__c> getAllVisits(Id userId) {
        List<Visit__c> visitList = [SELECT
                                        Id, Original_Date__c, Route_Id__c
                                    FROM
                                        Visit__c
                                    WHERE
                                        Seller__r.Related_User__c = :userId];
        return visitList;
    }
}