objects/Holiday__c.object
<CustomObject>
    <fields>
        <fullName>All_Day__c</fullName>
        <defaultValue>false</defaultValue>
        <label>All Day</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distributor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Holidays declared under respective distributors.</description>
        <label>Distributor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Holidays</relationshipLabel>
        <relationshipName>Holidays</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End__c</fullName>
        <label>End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Recurring_Holiday__c</fullName>
        <label>Recurring Holiday</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start</label>
        <type>DateTime</type>
    </fields>
    <label>Holiday</label>
    <nameField>
        <label>Holiday Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HolidayClass.cls
public class HolidayClass {
    
    @Auraenabled
    public static void getSaveHolidays(String holidayObject) {
        
        System.debug('######## '+holidayObject);
        HolidayWrpClass holidayVar = (HolidayWrpClass) System.JSON.deserialize(holidayObject, HolidayWrpClass.class);
        System.debug('holiday '+holidayVar);
        
        Holiday__c holidayInsert = new Holiday__c();
        holidayInsert.Name = holidayVar.HolidayName;
        holidayInsert.Distributor__c = holidayVar.parentID;
        holidayInsert.All_Day__c = holidayVar.AllDay;
        if(holidayVar.Description.length() > 0) {
            holidayInsert.Description__c = holidayVar.Description;
        }
        if(holidayVar.AllDay) {
            holidayInsert.Start__c = holidayVar.HolidayDate;
            holidayInsert.End__c = holidayVar.HolidayDate;
        } else {
            List< String > startHours = holidayVar.StartTime.split(':');
            List< String > endHours = holidayVar.EndTime.split(':');
            holidayInsert.Start__c = holidayVar.HolidayDate.addHours(Integer.ValueOf(startHours[0])).addMinutes(Integer.ValueOf(startHours[1]));
            holidayInsert.End__c = holidayVar.HolidayDate.addHours(Integer.ValueOf(endHours[0])).addMinutes(Integer.ValueOf(endHours[1]));
        }
        if(holidayVar.Recurring) {
            holidayInsert.Recurring_Holiday__c = holidayVar.RecurringText;
        }
        insert holidayInsert;
    }
}