objects/Picklist_Value_Id_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Id value config for global pick list values</description>
    <fields>
        <fullName>BrandId__c</fullName>
        <label>BrandId</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CategoryId__c</fullName>
        <label>CategoryId</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ChannelId__c</fullName>
        <label>ChannelId</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SubChannelId__c</fullName>
        <label>SubChannelId</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Picklist Value Id Config</label>
</CustomObject>

objects/Survey_Target__c.object
<CustomObject>
    <description>Created on 01-12-2016
Survey Target</description>
    <fields>
        <fullName>BrandCode__c</fullName>
        <globalPicklist>Product_Brand</globalPicklist>
        <label>BrandCode</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryCode__c</fullName>
        <globalPicklist>Product_Category</globalPicklist>
        <label>CategoryCode</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubChannelCode__c</fullName>
        <globalPicklist>ChannelCodePicklist</globalPicklist>
        <label>SubChannelCode</label>
        <type>Picklist</type>
    </fields>
    <label>Survey Target</label>
    <nameField>
        <label>Survey Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Target</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestRESTGoldenStoreTarget.cls
@isTest
private class TestRESTGoldenStoreTarget {
    static testMethod void goldenStoreTargetManager1() {
        Survey_Target__c surveyTarget = new Survey_Target__c();
        
        List<Picklist_Value_Id_Config__c> pvidList = new List<Picklist_Value_Id_Config__c> {
            new Picklist_Value_Id_Config__c(Name = 'DP OTC', BrandId__c = 1, SubChannelId__c = 110, ChannelId__c = 101),
            new Picklist_Value_Id_Config__c(Name = 'Laundry', BrandId__c = 2, CategoryId__c = 102),
            new Picklist_Value_Id_Config__c(Name = 'Ariel ', BrandId__c = 3, CategoryId__c = 103)
        };
        insert pvidList;
        
        surveyTarget.Name = 'Test survey Target';
        surveyTarget.SubChannelCode__c = 'DP OTC';
        surveyTarget.CategoryCode__c = 'Laundry';
        surveyTarget.BrandCode__c = 'Ariel';
        insert surveyTarget;
        List<SurveyTargetDomain.goldenStoreTargetInfo> goldenST = RESTGoldenStoreTarget.getGoldenStoreTarget();
    }
}