objects/Picklist_Value_Id_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Id value config for global pick list values</description>
    <fields>
        <fullName>BrandId__c</fullName>
        <label>BrandId</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CategoryId__c</fullName>
        <label>CategoryId</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ChannelId__c</fullName>
        <label>ChannelId</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SubChannelId__c</fullName>
        <label>SubChannelId</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Picklist Value Id Config</label>
</CustomObject>

classes/TestCategoryTranslator.cls
@isTest
public class TestCategoryTranslator {
    static testMethod void category1() {
         List<Picklist_Value_Id_Config__c> pvidList = new List<Picklist_Value_Id_Config__c> {
            new Picklist_Value_Id_Config__c(Name = 'test1', BrandId__c = 1, CategoryId__c = 101),
            new Picklist_Value_Id_Config__c(Name = 'test2', BrandId__c = 2, CategoryId__c = 102),
            new Picklist_Value_Id_Config__c(Name = 'test3', BrandId__c = 3, CategoryId__c = 103)
        };
        insert pvidList;
        List<Picklist_Value_Id_Config__c> picklistVals = new List<Picklist_Value_Id_Config__c> {
            new Picklist_Value_Id_Config__c(Name = 'test1', ChannelId__c = 1, SubChannelId__c = 101),
            new Picklist_Value_Id_Config__c(Name = 'test2', ChannelId__c = 2, SubChannelId__c = 102),
            new Picklist_Value_Id_Config__c(Name = 'test3', ChannelId__c = 3, SubChannelId__c = 103)
        };
        insert picklistVals;
        List<CategoryDomain.CategoryInfo> categoryList = CategoryTranslator.objectToCategoryInfo(pvidList);
        List<CategoryDomain.BrandInfo> brandList = CategoryTranslator.objectToBrandInfo(pvidList);
        List<CategoryDomain.ChannelInfo> channelList = CategoryTranslator.objectToChannelInfo(picklistVals);
        List<CategoryDomain.SubChannelInfo> subchannelList = CategoryTranslator.objectToSubChannelInfo(picklistVals);
    }
}