objects/Picklist_Value_Id_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Id value config for global pick list values</description>
    <fields>
        <fullName>BrandId__c</fullName>
        <label>BrandId</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CategoryId__c</fullName>
        <label>CategoryId</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Picklist Value Id Config</label>
</CustomObject>

classes/TestRestCategoryManager.cls
@isTest
private class TestRestCategoryManager {
    static testMethod void categoryManager1() {
        List<Picklist_Value_Id_Config__c> pvidList = new List<Picklist_Value_Id_Config__c> {
            new Picklist_Value_Id_Config__c(Name = 'test4', BrandId__c = 1, CategoryId__c = 101),
            new Picklist_Value_Id_Config__c(Name = 'test5', BrandId__c = 2, CategoryId__c = 102),
            new Picklist_Value_Id_Config__c(Name = 'test6 ', BrandId__c = 3, CategoryId__c = 103)
        };
        insert pvidList;
        List<CategoryDomain.CategoryInfo> categoryTrans = CategoryTranslator.objectToCategoryInfo(pvidList);
        
        List<CategoryDomain.CategoryInfo> catelist = RESTCategoryManager.getSurveyCategories();
    }
}