objects/Picklist_Value_Id_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Id value config for global pick list values</description>
    <fields>
        <fullName>BrandId__c</fullName>
        <label>BrandId</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CategoryId__c</fullName>
        <label>CategoryId</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ChannelId__c</fullName>
        <label>ChannelId</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Picklist Value Id Config</label>
</CustomObject>

objects/Survey_Target__c.object
<CustomObject>
    <description>Created on 01-12-2016
Survey Target</description>
    <fields>
        <fullName>BrandCode__c</fullName>
        <globalPicklist>Product_Brand</globalPicklist>
        <label>BrandCode</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryCode__c</fullName>
        <globalPicklist>Product_Category</globalPicklist>
        <label>CategoryCode</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubChannelCode__c</fullName>
        <globalPicklist>ChannelCodePicklist</globalPicklist>
        <label>SubChannelCode</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <label>Target</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Survey Target</label>
    <nameField>
        <label>Survey Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Target</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SurveyTargetTranslator.cls
public with sharing class SurveyTargetTranslator {

    public static List<SurveyTargetDomain.goldenStoreTargetInfo> objectToSurveyTargetInfo(List<Survey_Target__c> surveyTargets) {
        List<SurveyTargetDomain.goldenStoreTargetInfo> surveyTargetInfos = new List<SurveyTargetDomain.goldenStoreTargetInfo>();
        
        Map<String, Decimal> channelNameIdMap = new Map<String, Decimal>();
        Map<String, Decimal> categoryNameIdMap = new Map<String, Decimal>();
        Map<String, Decimal> brandNameIdMap = new Map<String, Decimal>();
        
        Set<String> channelNameSet = CategoryService.getAllChannelNames();
        if (channelNameSet != null && channelNameSet.size() > 0) {
            channelNameIdMap = SurveyTargetTranslator.getPicklistValueIdMap(CategoryService.getChannelsByName(channelNameSet), 'channel');
        }
        
        Set<String> categoriesNameSet = CategoryService.getAllCategories();
        if (categoriesNameSet != null && categoriesNameSet.size() > 0) {
            categoryNameIdMap = SurveyTargetTranslator.getPicklistValueIdMap(CategoryService.getCategoryIdsByName(categoriesNameSet), 'category');
        }
        
        Set<String> brandNameSet = CategoryService.getAllBrandNames();
        if (brandNameSet != null && brandNameSet.size() > 0) {
            brandNameIdMap = SurveyTargetTranslator.getPicklistValueIdMap(CategoryService.getBrandsByName(brandNameSet), 'brand');
        }
        
        for (Survey_Target__c surTarget: surveyTargets) {
            SurveyTargetDomain.goldenStoreTargetInfo surveyTargetInfo = new SurveyTargetDomain.goldenStoreTargetInfo();
            if (surTarget.SubChannelCode__c != null && channelNameIdMap.containsKey(surTarget.SubChannelCode__c)) {
                surveyTargetInfo.ChannelId = channelNameIdMap.get(surTarget.SubChannelCode__c);
            }
            if (surTarget.CategoryCode__c != null && categoryNameIdMap.containsKey(surTarget.CategoryCode__c)) {
                surveyTargetInfo.CategoryId = categoryNameIdMap.get(surTarget.CategoryCode__c);
            }
            if (surTarget.BrandCode__c != null && brandNameIdMap.containsKey(surTarget.BrandCode__c)) {
                surveyTargetInfo.BrandId = brandNameIdMap.get(surTarget.BrandCode__c);
            }
            surveyTargetInfo.Target = surTarget.Target__c;
            surveyTargetInfos.add(surveyTargetInfo);
        } 
        return surveyTargetInfos;
    }
    
    public static Map<String, Decimal> getPicklistValueIdMap(List<Picklist_Value_Id_Config__c> picklistValueIds, String picklistType) {
        Map<String, Decimal> responsePicklistNameIdMap = new Map<String, Decimal>();
        
        if (picklistValueIds != null && picklistValueIds.size() > 0) {
            for (Picklist_Value_Id_Config__c pvid :picklistValueIds) {
                if (picklistType == 'channel' && pvid.ChannelId__c != null) {
                    responsePicklistNameIdMap.put(pvid.Name, pvid.ChannelId__c);
                } else if (picklistType == 'category' && pvid.CategoryId__c != null) {
                    responsePicklistNameIdMap.put(pvid.Name, pvid.CategoryId__c);
                } else if (picklistType == 'brand' && pvid.BrandId__c != null) {
                    responsePicklistNameIdMap.put(pvid.Name, pvid.BrandId__c);
                }
            }   
        }
        return responsePicklistNameIdMap;
    }
}