objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey_Code__c</fullName>
        <label>Survey Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RESTSurveyController.cls
@RestResource(urlMapping='/FieldSurvey/*')
global with sharing class RESTSurveyController {


@HttpPost
    global static String createNewSurvey(String surveyName, Boolean active, String surveyCode) {
        System.debug('RII Rest1');
        Survey__c s = new Survey__c();
        s.Name = surveyName;
        s.Active__c = active;
        s.Survey_Code__c = surveyCode;
        insert s;
        
        return 'Survey Created for ivymobility using restapi '+s;
    }
    
}