objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Store_Local_Channel__c</fullName>
        <globalPicklist>Local_Channel</globalPicklist>
        <label>Store Local Channel</label>
        <type>Picklist</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Questions</relationshipLabel>
        <relationshipName>Survey_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ-{000}</displayFormat>
        <label>Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ShowSurveyQuestionsController.cls
Public with Sharing class ShowSurveyQuestionsController {
    
    public Survey__c survey { get; set; }
    public List<Survey_Question__c> surveyQuestionList { get; set; }
    
    public ShowSurveyQuestionsController() {
        this.survey = new Survey__c();
        this.survey.Store_Local_Channel__c = null;
        surveyQuestionList = new List<Survey_Question__c> ();
    }
    
    public void resetFilters() {
        this.survey = new Survey__c();
        this.survey.Store_Local_Channel__c = null;
        surveyQuestionList = new List<Survey_Question__c>();
    }
    
    public void searchSurveyQuestion() {
        surveyQuestionList = SurveyQuestionService.searchSurveyQuestionwithSurvey(this.survey);
        system.debug('list::::size'+surveyQuestionList.size());
    }
}