objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <globalPicklist>Product_Category</globalPicklist>
        <label>Product Category</label>
        <type>Picklist</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Questions</relationshipLabel>
        <relationshipName>Survey_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ-{000}</displayFormat>
        <label>Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/surveyPageFormController.cls
public with sharing class surveyPageFormController {
    @AuraEnabled
	public static List<Survey_Question__c> getSurveyQuestionList(Survey__c surveyval) {
        list<Survey__c> surveyList = [SELECT ID, Name FROM Survey__c WHERE Product_Category__c Like: '%'+surveyval.Product_Category__c+'%'];
        list<ID> surveyIDList = new list<ID>();
        list<Survey_Question__c> surveyQuesList = new list<Survey_Question__c>();
        
        if(surveyList.size() > 0) {
            for(Survey__c tempsurvey : surveyList) {
                surveyIDList.add(tempsurvey.ID);
            }
        }
        
        surveyQuesList = [SELECT ID, Question__c FROM Survey_Question__c WHERE Survey__c IN: surveyIDList];
        if(surveyQuesList.size() > 0)
            return surveyQuesList;
        return null;
    }
}