objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Product_Brand__c</fullName>
        <globalPicklist>Product_Brand</globalPicklist>
        <label>Product Brand</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <globalPicklist>Product_Category</globalPicklist>
        <label>Product Category</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Sub_Brand__c</fullName>
        <globalPicklist>Product_Sub_Brand</globalPicklist>
        <label>Product Sub Brand</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Store_Channel__c</fullName>
        <globalPicklist>ChannelCodePicklist</globalPicklist>
        <label>Store Channel</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Store_Local_Channel__c</fullName>
        <globalPicklist>Local_Channel</globalPicklist>
        <label>Store Local Channel</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <type>DateTime</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Question_Code__c</fullName>
        <label>Question Code</label>
        <picklist>
            <picklistValues>
                <fullName>IAA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IAV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IAF</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question_Id__c</fullName>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <picklist>
            <picklistValues>
                <fullName>Yes/No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integer Text</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Questions</relationshipLabel>
        <relationshipName>Survey_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <label>Target</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Weightage__c</fullName>
        <label>Weightage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ-{000}</displayFormat>
        <label>Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SurveyQuestionService.cls
public class SurveyQuestionService {
    public static List<Survey_Question__c> searchSurveyQuestionwithSurvey(Survey__c survey) {
        String productCategory = survey.Product_Category__c;
        String productBrand = survey.Product_Brand__c;
        String subBrand = survey.Product_Sub_Brand__c;
        String storeChannel = survey.Store_Channel__c;
        String localChannel = survey.Store_Local_Channel__c;
        
        
        String surveyQueryStr = 'SELECT '
                                        + 'Id, '
                                        + 'Name, '
                                        + 'Survey__c, '
                                        + 'Survey__r.Name, '
                                        + 'Survey__r.Product_Category__c, '
                                        + 'Survey__r.Product_Brand__c, '
                                        + 'Survey__r.Product_Sub_Brand__c, '
                                        + 'Survey__r.Store_Channel__c, '
                                        + 'Survey__r.Store_Local_Channel__c, '
                                        + 'Question__c, '
                                        + 'Question_Code__c, '
                                        + 'Question_Id__c, '
                                        + 'Question_Type__c, '
                                        + 'Target__c, '
                                        + 'Weightage__c, '
                                        + 'From__c, '
                                        + 'To__c '
                                + 'FROM '
                                    + 'Survey_Question__c '
                                + 'WHERE '
                                    + 'Survey__c != NULL ';
        if(survey != null) {
            if (productCategory != null) {
                surveyQueryStr += ' AND Survey__r.Product_Category__c = :productCategory';
            }
            if (productBrand != null) {
                surveyQueryStr += ' AND Survey__r.Product_Brand__c = :productBrand ';
            }
            if (subBrand != null) {
                surveyQueryStr += ' AND Survey__r.Product_Sub_Brand__c = :subBrand ';
            }
            if (storeChannel != null) {
                surveyQueryStr += ' AND Survey__r.Store_Channel__c = :storeChannel ';
            }
            if (localChannel != null) {
                surveyQueryStr += ' AND Survey__r.Store_Local_Channel__c = :localChannel ';
            }
        }
        surveyQueryStr += ' LIMIT 1000';
        
        return Database.Query(surveyQueryStr);
    }
}