objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Product_Brand__c</fullName>
        <globalPicklist>Product_Brand</globalPicklist>
        <label>Product Brand</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <globalPicklist>Product_Category</globalPicklist>
        <label>Product Category</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Sub_Brand__c</fullName>
        <globalPicklist>Product_Sub_Brand</globalPicklist>
        <label>Product Sub Brand</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Store_Channel__c</fullName>
        <globalPicklist>ChannelCodePicklist</globalPicklist>
        <label>Store Channel</label>
        <type>Picklist</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestSurveyPageFormController.cls
/**********************************************************************\
    @ Author        : Souravmoy Gorai
    @ Date          : December 15, 2016
    @ Test File     : Yes
    @ Function      : Test Class for surveyPageFormController
***********************************************************************/

@isTest
private class TestSurveyPageFormController {

    static testMethod void myUnitTest() {
    	Test.startTest();
    		Survey__c testSurvey1 = TestDataUtility.createSurveyTestData('ADM','Old Spice','APDO','DP OTC','DP OTC');
    		Database.insert(testSurvey1);
    		Survey__c testSurvey2 = TestDataUtility.createSurveyTestData('Baby Care','Pampers','Diapers','DP OTC','DP OTC');
    		Database.insert(testSurvey2);
    		
    		Survey__c searchSurvey = new Survey__c(Product_Sub_Brand__c='', Product_Brand__c='', Product_Category__c='ADM', Store_Channel__c='', Name='');
    		surveyPageFormController.getSurveyQuestionList(searchSurvey);
    	Test.stopTest();
    }
}