objects/Survey_Target__c.object
<CustomObject>
    <description>Created on 01-12-2016
Survey Target</description>
    <fields>
        <fullName>BrandCode__c</fullName>
        <globalPicklist>Product_Brand</globalPicklist>
        <label>BrandCode</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryCode__c</fullName>
        <globalPicklist>Product_Category</globalPicklist>
        <label>CategoryCode</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubChannelCode__c</fullName>
        <globalPicklist>ChannelCodePicklist</globalPicklist>
        <label>SubChannelCode</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <label>Target</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Survey Target</label>
    <nameField>
        <label>Survey Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Target</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SurveyTargetService.cls
public with sharing class SurveyTargetService {
     public static List<Survey_Target__c> getAllSurveyTarget() {
        List<Survey_Target__c> surveyTargets;
        surveyTargets = [ SELECT Id,
                            SubChannelCode__c,
                            CategoryCode__c,
                            BrandCode__c, 
                            Target__c
                          FROM
                            Survey_Target__c];
        return surveyTargets;
    }
}