objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Survey_Code__c</fullName>
        <label>Survey Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <type>DateTime</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Question_Code__c</fullName>
        <label>Question Code</label>
        <picklist>
            <picklistValues>
                <fullName>IAA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IAV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IAF</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <picklist>
            <picklistValues>
                <fullName>Yes/No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integer Text</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey_Code__c</fullName>
        <formula>Survey__r.Survey_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Survey Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Questions</relationshipLabel>
        <relationshipName>Survey_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <type>DateTime</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ-{000}</displayFormat>
        <label>Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SurveyTranslator.cls
public with sharing class SurveyTranslator {
    public static List<SurveyDomain.SurveyInfo> ObjectToDomain(List<Survey__c> surveys) {
        List<SurveyDomain.SurveyInfo> surveyInfos = new List<SurveyDomain.SurveyInfo>();
        for(Survey__c survey : surveys) {
            surveyInfos.add(ObjectToDomain(survey));
        }
        return surveyInfos;
    }

    public static SurveyDomain.SurveyInfo ObjectToDomain(Survey__c survey) {
        SurveyDomain.SurveyInfo surveyInfo = new SurveyDomain.SurveyInfo();
        surveyInfo.Posm = new List<SurveyDomain.SurveyQuestionInfo>();
        for(Survey_Question__c question : survey.Survey_Questions__r) {
            surveyInfo.Posm.add(ObjectToDomain(question));
        }
        return surveyInfo;
    }
    
    public static SurveyDomain.SurveyQuestionInfo ObjectToDomain(Survey_Question__c question) {
        SurveyDomain.SurveyQuestionInfo questionInfo = new SurveyDomain.SurveyQuestionInfo();
        questionInfo.QuestionId = question.Question_Code__c;
        questionInfo.QuestionDesc = question.Name;
        questionInfo.ListCode = (question.Question_Type__c=='Yes/No')? 'Option':'Text';
        return questionInfo;
    }
    
    public static List<SurveyDomain.SurveyMasterInfo> objectToSurveyMasterInfo(List<Survey__c> surveys) {
        List<SurveyDomain.SurveyMasterInfo> surveyMasterInfos = new List<SurveyDomain.SurveyMasterInfo>();
        for (Survey__c survey: surveys) {
            SurveyDomain.SurveyMasterInfo surveyInfo = new SurveyDomain.SurveyMasterInfo();
            surveyInfo.SurveyId = survey.Survey_Code__c;
            surveyInfo.SurveyDesc = survey.Name;
            surveyInfo.StartDate = survey.From__c;
            surveyInfo.EndDate = survey.To__c;
            surveyMasterInfos.add(surveyInfo);
        } 
        return surveyMasterInfos;
    }
}