objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Question_Id__c</fullName>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ-{000}</displayFormat>
        <label>Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey_Result_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Actual__c</fullName>
        <label>Actual</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Survey Results Detail</relationshipLabel>
        <relationshipName>Survey_Results_Detail</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Survey Result Detail</label>
    <nameField>
        <label>Survey Result Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Results Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SurveyResultDetailTranslator.cls
public with sharing class SurveyResultDetailTranslator {
    public static List<SurveyResultDetailDomain.SurveyResultDetailInfo> objectToSurveyResultDetailInfo(List<Survey_Result_Detail__c> surveyResultDetailList) {
        List<SurveyResultDetailDomain.SurveyResultDetailInfo> surveyResultDetailInfoList = new List<SurveyResultDetailDomain.SurveyResultDetailInfo>();
        
        for(Survey_Result_Detail__c surveyResultDetail : SurveyResultDetailList) {
            SurveyResultDetailDomain.SurveyResultDetailInfo surveyResultDetailInfo = new SurveyResultDetailDomain.SurveyResultDetailInfo();
            if (surveyResultDetail.Survey_Question__c != null && surveyResultDetail.Survey_Question__r.Question_Id__c != null) {
                surveyResultDetailInfo.QuestionId = Integer.valueOf(surveyResultDetail.Survey_Question__r.Question_Id__c);
            }
            surveyResultDetailInfo.Answer = surveyResultDetail.Actual__c;
            surveyResultDetailInfoList.add(surveyResultDetailInfo);
        }
        return SurveyResultDetailInfoList;
    }
}